# Generated by Django 3.2.15 on 2022-11-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('py_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
