# Generated by Django 3.1.6 on 2023-12-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('park', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('py_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('amount', models.CharField(default='200', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=100)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
