# Generated by Django 3.2.15 on 2022-11-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('s_id', models.IntegerField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
    ]
