# Generated by Django 5.0 on 2023-12-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.CharField(max_length=10)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
