# Generated by Django 5.0 on 2023-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
