# Generated by Django 3.2.15 on 2022-11-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'park',
                'managed': False,
            },
        ),
    ]
